//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FinanceManagementEntities : DbContext
    {
        public FinanceManagementEntities()
            : base("name=FinanceManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActivityLog> ActivityLogs { get; set; }
        public DbSet<AdminCredential> AdminCredentials { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<EMICard> EMICards { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<Product> Products { get; set; }
    
        public virtual ObjectResult<sp_login_Result> sp_login(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_login_Result>("sp_login", usernameParameter, passwordParameter);
        }
    
        public virtual int sp_GenerateCardID(ObjectParameter cardNum)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GenerateCardID", cardNum);
        }
    }
}
