//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int TransactionID { get; set; }
        public Nullable<int> RegNumber { get; set; }
        public string CardID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public int Quantity { get; set; }
        public int TotalAmount { get; set; }
        public int EMIDuration { get; set; }
        public int EMIPaid { get; set; }
        public int EMIBalance { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual EMICard EMICard { get; set; }
        public virtual Product Product { get; set; }
    }
}
